[Feat] #2 TabBarView 구현
EZPZapp/EZPZ pull request #14
Opened 2022-10-20 16:01 UTC by Juhwa-Lee1023

### Motivation
- #2 
- TabBar를 이용하여 뷰를 이동하는 앱이기에 TabBar를 구현하였습니다.

### Key Change
- `TabBarView`를 시작 뷰로 변경하였습니다.
-  TabBar를 구현하였습니다.
<img width="353" alt="image" src="https://user-images.githubusercontent.com/63584245/196999368-6dabfc72-69d3-4556-ba61-556270f21d06.png">

### To Reviewers
- `오늘할일`과 `내도전`의 아이콘은 린다에게 아이콘 전달받으면 변경하도록 하겠습니다.

2022-10-20 17:45 UTC, yeniful requested changes

2022-10-20 17:45 UTC, yeniful commented on EZPZ/EZPZ/Views/TabBarView.swift
> +        UITabBar.appearance().backgroundColor = UIColor(Color("EZPZBlack"))
가장 처음에 색 지정을 해주는군요!

2022-10-20 17:45 UTC, yeniful commented on EZPZ/EZPZ/Views/TabBarView.swift
> +                }.tag(0)
태그와 tabBarIndex를 통해 탭뷰에 해당하는 화면으로 이동하는군요!

2022-10-20 17:45 UTC, yeniful commented on EZPZ/EZPZ/Views/TabBarView.swift
> +    @State var tabBarIndex: Int = 0
SwiftUI에서는 `tabBar`가 아닌 `tabView`로 사용하더라고요 SwiftUI스럽게 `tabViewIndex` 로 바꾸는건 어떨지 제안해봅니다!

2022-10-20 17:46 UTC, Juhwa-Lee1023 commented on EZPZ/EZPZ/Views/TabBarView.swift
> +        UITabBar.appearance().backgroundColor = UIColor(Color("EZPZBlack"))
넵. 맞습니다!

2022-10-20 17:47 UTC, Juhwa-Lee1023 commented on EZPZ/EZPZ/Views/TabBarView.swift
> +                }.tag(0)
넵! 정확합니다.

2022-10-20 17:47 UTC, Juhwa-Lee1023 commented on EZPZ/EZPZ/Views/TabBarView.swift
> +    @State var tabBarIndex: Int = 0
좋은 생각이네요! 바로 수정하도록 하겠습니다.

2022-10-20 17:49 UTC, yeniful requested changes

2022-10-20 17:49 UTC, yeniful commented on EZPZ/EZPZ/Views/TabBarView.swift
> +    @State var tabBarIndex: Int = 0
```suggestion
    @State var tabViewIndex: Int = 0
```

2022-10-20 17:49 UTC, yeniful commented on EZPZ/EZPZ/Views/TabBarView.swift
> +            imsi(check: tabBarIndex)
```suggestion
            imsi(check: tabViewIndex)
```

2022-10-20 17:49 UTC, yeniful commented on EZPZ/EZPZ/Views/TabBarView.swift
> +            imsi(check: tabBarIndex)
```suggestion
            imsi(check: tabViewIndex)
```

2022-10-20 17:49 UTC, yeniful commented on EZPZ/EZPZ/Views/TabBarView.swift
> +            imsi(check: tabBarIndex)
```suggestion
            imsi(check: tabViewIndex)
```

2022-10-20 17:49 UTC, yeniful commented on EZPZ/EZPZ/Views/TabBarView.swift
> +            imsi(check: tabBarIndex)
```suggestion
            imsi(check: tabViewIndex)
```

2022-10-20 17:55 UTC, Juhwa-Lee1023 commented on EZPZ/EZPZ/Views/TabBarView.swift
> +    @State var tabBarIndex: Int = 0
넵 감사합니다!

2022-10-20 17:57 UTC, Juhwa-Lee1023 commented on EZPZ/EZPZ/Views/TabBarView.swift
> +            imsi(check: tabBarIndex)
넵 감사합니다!
바로 수정하였습니다.
cb008ee0e962870dc3d3ba4d64301e0565df1048

2022-10-20 17:57 UTC, Juhwa-Lee1023 commented on EZPZ/EZPZ/Views/TabBarView.swift
> +            imsi(check: tabBarIndex)
넵 감사합니다!
바로 수정하였습니다.
cb008ee0e962870dc3d3ba4d64301e0565df1048

2022-10-20 17:57 UTC, Juhwa-Lee1023 commented on EZPZ/EZPZ/Views/TabBarView.swift
> +            imsi(check: tabBarIndex)
넵 감사합니다!
바로 수정하였습니다.
cb008ee0e962870dc3d3ba4d64301e0565df1048

2022-10-20 17:57 UTC, Juhwa-Lee1023 commented on EZPZ/EZPZ/Views/TabBarView.swift
> +            imsi(check: tabBarIndex)
넵 감사합니다!
바로 수정하였습니다.
cb008ee0e962870dc3d3ba4d64301e0565df1048

2022-10-21 05:59 UTC, Hongjaaa commented
tab view 구현 코드 잘 읽었습니다! 감사합니다!

2022-10-21 06:00 UTC, Hongjaaa approved these changes

2022-10-21 06:00 UTC, Hongjaaa commented on EZPZ/EZPZ/Views/TabBarView.swift
> +        UITabBar.appearance().unselectedItemTintColor = UIColor(Color("Grayscale2"))
선택하지 않았을 때의 색 지정이군요!

2022-10-22 08:29 UTC, Juhwa-Lee1023 commented on EZPZ/EZPZ/Views/TabBarView.swift
> +        UITabBar.appearance().unselectedItemTintColor = UIColor(Color("Grayscale2"))
넵! 맞습니다. 메소드 이름이 엄청 직관적이더라고요.

2022-10-22 09:19 UTC, merged